service: serverless-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "dynamodb:*"
          Resource: "*"

functions:
  handlerGet:
    handler: index.handlerGet
  handlerUpdate:
    handler: index.handlerUpdate
  handlerPut:
    handler: index.handlerPut
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:746204573428:table/UserID/stream/2023-03-28T03:58:51.308
          batchSize: 10
          startingPosition: LATEST
