service: serverless-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "dynamodb:*"
            - "s3:*"
          Resource: "*"

functions:
  handlerGet:
    handler: index.handlerGet
    events:
      - http:
          path: /
          method: get
          cors: true

  handlerUpdate:
    handler: index.handlerUpdate
    events:
      - http:
          path: /
          method: post
          cors: true
  handlerPut:
    handler: index.handlerPut
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:746204573428:table/UserID/stream/2023-03-28T03:58:51.308
          batchSize: 10
          startingPosition: LATEST

  ChBucket:
    handler: index.ChBucket
    events:
      - http:
          path: /
          method: post
          cors: true

  ChFilePrint:
    handler: index.ChFilePrint
    events:
      - s3:
          bucket: ch-bucket-yaml
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    chbucketyaml:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ch-bucket-yaml
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - "GET"
                - "POST"
                - "PUT"
              AllowedOrigins:
                - "*"
    SampleBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref chbucketyaml
        PolicyDocument:
          Statement:
            - Action:
                - "s3:GetObject"
                - "s3:PutObject"
                - "s3:PutObjectAcl"
              Effect: Allow
              Resource:
                - "arn:aws:s3:::ch-bucket-yaml/*"
              Principal: "*"
